version: "3.9"
networks:
  service-network:

services:
  wiremock-service:
    hostname: wiremock
    image: wiremock-img
    container_name: wiremock-service
    build:
      context: .
      dockerfile: docker-files/wiremock.Dockerfile
    ports:
      - "8083:8083"
    networks:
      - service-network

  service:
    container_name: service
    environment:
      TRANSLATION_SERVICE_URL: http://wiremock:8083/translation-service/GUID/to/NINO/
    build:
      context: .
      dockerfile: docker-files/appointment-service.Dockerfile
    ports:
      - "8082:8082"
    networks:
      - service-network